language: generic

services:
    - docker

before_install:
    - docker build -t dev2peak/simple-frontend -f Dockerfile.dev .

script:
    - docker run -e CI=true dev2peak/simple-frontend npm run test